### PR TITLE
Fix version placeholder

### PR DESCRIPTION
**Pull request by kjellkvinge**

### CODE REVIEW

**Comment by kjellkvinge** [comment]
sorry, reference to issue was a typo

**Comment by kovetskiy** [comment]
@kjellkvinge thanks, nice catch, can you please edit commit message and remove reference to issue?

**Comment by kjellkvinge** [comment]
@kovetskiy fixed

**Comment by kovetskiy** [comment]
@kjellkvinge thanks, merged!

**Pull request merged**
